import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Static metadata can still be exported in JS (just without typing).... Static metadata means that this is not going to be changed later
export const metadata = {
  title: "Create Next App", //In Next.js this is how page title and description is defined
  description: "Generated by create next app", 
};

export default function RootLayout({ children }) {   //That children is a special React prop that contains anything nested inside your component.
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
